// Centralized projects data
export const projectsData = [
  {
    id: 1,
    slug: "rizzer",
    title: "Rizzer",
    subtitle: "Your AI Dating Coach",
    category: "Mobile App",
    tags: ["AI", "React Native", "Dating"],
    year: "2024",
    image: "https://images.unsplash.com/photo-1516251193007-45ef944ab0c6?q=80&w=2070",
    color: "from-pink-500 to-rose-500",
    featured: true,
    description: "Master modern dating with AI-powered conversation starters, personalized date ideas, and intelligent relationship management.",
    longDescription: "Rizzer is your personal AI dating coach that helps you spark conversations, plan perfect dates, and build meaningful connections. It combines AI intelligence with dating psychology to give you personalized conversation starters, date ideas, and relationship insights that actually work.",
    challenge: "Modern dating is hard. Swiping is easy, but building real connections is where most people struggle. Many people overthink messages, run out of things to say, or struggle to plan memorable dates.",
    solution: "Built an AI-powered dating assistant that learns your style, understands your matches, and helps you build authentic connections. Features include context-aware conversation starters, screenshot analysis for smart replies, and a unique 'Sherlock' gift investigation feature.",
    features: [
      "AI-powered conversation starters & witty responses",
      "Screenshot analysis for smart reply suggestions",
      "Date profile management with compatibility scores",
      "AI-crafted date ideas based on location & budget",
      "Sherlock gift investigation via WhatsApp/iMessage",
      "Multiple conversation tones (Flirty, Funny, Smooth, Spicy)",
      "24/7 AI dating strategist chat",
      "Birthday and milestone reminders"
    ],
    results: [
      "Thousands of active users",
      "Featured on App Store & Google Play",
      "4.8+ star rating",
      "Users report 3x more successful dates"
    ],
    technologies: ["React Native", "OpenAI", "Node.js", "PostgreSQL", "WhatsApp API", "AWS"],
    liveUrl: "https://rizzer.io/",
    platforms: ["iOS", "Android"]
  },
  {
    id: 2,
    slug: "night-owl",
    title: "Night Owl",
    subtitle: "The city sleeps. We don't.",
    category: "Mobile App",
    tags: ["React Native", "AI", "Social"],
    year: "2024",
    image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?q=80&w=2070",
    color: "from-indigo-600 to-purple-600",
    featured: true,
    description: "A safe, anonymous social space for night owls. Connect through mood-based matching, share thoughts, and join live audio lounges.",
    longDescription: "Night Owl is a revolutionary mobile app designed for people who come alive after dark. Unlike traditional social apps that focus on photos and profiles, Night Owl connects users based on their current mood and emotional state.",
    challenge: "Create a social platform that prioritizes emotional connection over superficial metrics, while maintaining user safety and anonymity in late-night interactions.",
    solution: "Built a mood-based matching algorithm that connects users feeling the same way. Implemented anonymous profiles, real-time chat, and live audio lounges for authentic late-night conversations.",
    features: [
      "Mood-based matching with 12+ emotional states",
      "Anonymous profiles — no photos required",
      "Live audio lounges for group conversations",
      "Real-time chat with disappearing messages",
      "Night mode optimized UI",
      "Premium subscription with Night Owl+"
    ],
    results: [
      "10,000+ downloads in first month",
      "4.8 star rating on App Store",
      "Average session time of 45 minutes",
      "Featured in 'Apps We Love'"
    ],
    technologies: ["React Native", "Node.js", "Socket.io", "PostgreSQL", "AWS", "OpenAI"],
    liveUrl: "https://getnightowl.app/",
    platforms: ["iOS", "Android"]
  },
  {
    id: 3,
    slug: "nourishr",
    title: "Nourishr",
    subtitle: "Decide What to Eat in 5 Seconds",
    category: "Mobile App",
    tags: ["AI", "Computer Vision", "Health"],
    year: "2024",
    image: "https://images.unsplash.com/photo-1490818387583-1baba5e638af?q=80&w=2032",
    color: "from-emerald-500 to-teal-500",
    featured: true,
    description: "Your AI meal companion. Understand your cravings, dietary needs, and what's in your fridge to instantly recommend the perfect meal.",
    longDescription: "Nourishr eliminates decision fatigue around food. Using advanced AI and computer vision, it understands your mood, scans your ingredients, and recommends personalized meals in seconds.",
    challenge: "The average person spends 250+ hours a year deciding what to eat. Create an AI-powered solution that makes meal decisions instant and personalized.",
    solution: "Developed an AI recommendation engine that learns user preferences, combined with computer vision for ingredient scanning and nutritional analysis.",
    features: [
      "AI meal recommendations in 5 seconds",
      "Snap ingredients for instant recipes",
      "Smart pantry tracking with expiration alerts",
      "Photo-based nutritional analysis",
      "Integration with UberEats & DoorDash",
      "12+ dietary patterns supported"
    ],
    results: [
      "10,000+ active users",
      "250+ hours saved per user annually",
      "95% recommendation accuracy",
      "40% reduction in food waste"
    ],
    technologies: ["React Native", "Python", "TensorFlow", "OpenAI Vision", "Supabase", "AWS"],
    liveUrl: "https://nourishr.app/",
    platforms: ["iOS", "Android"]
  },
  {
    id: 4,
    slug: "nabsta",
    title: "Nabsta",
    subtitle: "Your Neighborhood Marketplace",
    category: "Web & Mobile App",
    tags: ["Marketplace", "Full-Stack", "Geolocation"],
    year: "2024",
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=2070",
    color: "from-orange-500 to-red-500",
    featured: true,
    description: "Buy and sell locally. Find amazing deals just around the corner. Fast, safe, and free.",
    longDescription: "Nabsta reimagines the local marketplace experience. With hyperlocal discovery, verified profiles, and safe meetup spots, it makes buying and selling in your neighborhood seamless and secure.",
    challenge: "Local marketplaces are broken — cluttered with spam, unsafe transactions, and poor user experience. Build a modern, trustworthy alternative.",
    solution: "Created a hyperlocal marketplace with verified profiles, secure messaging, safe meetup spot suggestions, and real-time fraud protection.",
    features: [
      "Hyperlocal discovery — see items nearby",
      "Snap, list, sell in under 60 seconds",
      "Verified profiles and secure messaging",
      "Safe meetup spot recommendations",
      "Seller analytics dashboard",
      "Multi-category: Sales, Jobs, Rentals, Services"
    ],
    results: [
      "Thousands of active listings",
      "60-second average listing time",
      "Zero fraud incidents reported",
      "4.9 star user satisfaction"
    ],
    technologies: ["Next.js", "React Native", "Node.js", "PostgreSQL", "Mapbox", "Stripe"],
    liveUrl: "https://nabsta.app/",
    platforms: ["Web", "iOS", "Android"]
  },
  {
    id: 5,
    slug: "nomerlo",
    title: "Nomerlo",
    subtitle: "Find Your Perfect Residence",
    category: "Web App",
    tags: ["Real Estate", "Full-Stack", "Search"],
    year: "2024",
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=2073",
    color: "from-blue-500 to-cyan-500",
    featured: false,
    description: "A modern real estate platform that helps you discover and find your perfect home with intelligent search and beautiful listings.",
    longDescription: "Nomerlo transforms the home search experience with an intuitive interface, smart filters, and comprehensive property details that help users find their dream residence.",
    challenge: "Traditional real estate platforms are cluttered and overwhelming. Create a clean, modern experience that makes finding a home enjoyable.",
    solution: "Built a streamlined property search platform with intelligent filtering, beautiful property showcases, and a focus on user experience.",
    features: [
      "Intelligent property search",
      "Advanced filtering options",
      "High-quality property galleries",
      "Neighborhood insights",
      "Saved searches and alerts",
      "Direct agent contact"
    ],
    results: [
      "50% faster property discovery",
      "High user engagement rates",
      "Streamlined agent connections"
    ],
    technologies: ["Next.js", "TypeScript", "Supabase", "Tailwind CSS", "Mapbox"],
    liveUrl: "https://nomerlo.lovable.app/",
    platforms: ["Web"]
  },
  {
    id: 6,
    slug: "nerxus",
    title: "Nerxus",
    subtitle: "Next-Gen Networking Platform",
    category: "Web App",
    tags: ["SaaS", "Networking", "Full-Stack"],
    year: "2024",
    image: "https://images.unsplash.com/photo-1551434678-e076c223a692?q=80&w=2070",
    color: "from-violet-500 to-purple-500",
    featured: false,
    description: "A professional networking platform designed for meaningful connections and career growth.",
    longDescription: "Nerxus reimagines professional networking with intelligent matching, streamlined communication, and tools designed for genuine relationship building.",
    challenge: "Professional networking platforms are noisy and impersonal. Create a focused platform for meaningful professional connections.",
    solution: "Developed a networking platform with smart matching algorithms and streamlined communication tools.",
    features: [
      "Intelligent professional matching",
      "Streamlined messaging",
      "Event discovery and networking",
      "Profile optimization tools",
      "Connection insights"
    ],
    results: [
      "Higher quality connections",
      "Improved response rates",
      "Active professional community"
    ],
    technologies: ["React", "Node.js", "PostgreSQL", "Redis", "AWS"],
    liveUrl: "https://preview--nerxus.lovable.app/",
    platforms: ["Web"]
  },
  {
    id: 7,
    slug: "clear-audio-ai",
    title: "Clear Audio AI",
    subtitle: "Crystal Clear Audio, Powered by AI",
    category: "Web App",
    tags: ["AI", "Audio Processing", "SaaS"],
    year: "2024",
    image: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?q=80&w=2070",
    color: "from-cyan-500 to-blue-500",
    featured: false,
    description: "AI-powered audio enhancement tool that removes background noise and improves audio quality instantly.",
    longDescription: "Clear Audio AI uses advanced machine learning to clean up audio recordings, remove background noise, and enhance voice clarity for podcasters, content creators, and professionals.",
    challenge: "Poor audio quality ruins content. Create an accessible AI tool that makes professional-grade audio enhancement available to everyone.",
    solution: "Built an AI-powered audio processing pipeline that removes noise, enhances clarity, and optimizes audio in seconds.",
    features: [
      "One-click noise removal",
      "Voice enhancement and clarity",
      "Background noise suppression",
      "Batch processing support",
      "Multiple export formats",
      "Real-time preview"
    ],
    results: [
      "90% noise reduction accuracy",
      "Processing in under 30 seconds",
      "Used by 1000+ content creators"
    ],
    technologies: ["Python", "TensorFlow", "React", "FastAPI", "AWS Lambda"],
    liveUrl: "https://preview--clear-audio-ai.lovable.app/",
    platforms: ["Web"]
  },
  {
    id: 8,
    slug: "mixguidera",
    title: "MixGuidera",
    subtitle: "Your AI Mixing Assistant",
    category: "Web App",
    tags: ["AI", "Music", "Audio"],
    year: "2024",
    image: "https://images.unsplash.com/photo-1598653222000-6b7b7a552625?q=80&w=2070",
    color: "from-pink-500 to-rose-500",
    featured: false,
    description: "AI-powered mixing assistant that helps music producers achieve professional-quality mixes.",
    longDescription: "MixGuidera analyzes your tracks and provides intelligent suggestions for EQ, compression, and effects to help you achieve radio-ready mixes.",
    challenge: "Music mixing has a steep learning curve. Create an AI assistant that guides producers toward professional-quality results.",
    solution: "Developed an AI that analyzes audio tracks and provides actionable mixing recommendations based on genre and reference tracks.",
    features: [
      "AI mix analysis",
      "Genre-specific recommendations",
      "Reference track comparison",
      "EQ and compression suggestions",
      "Real-time feedback"
    ],
    results: [
      "Faster mixing workflow",
      "Improved mix quality for beginners",
      "Active producer community"
    ],
    technologies: ["React", "Python", "TensorFlow", "Web Audio API", "Supabase"],
    liveUrl: "https://preview--mixguidera.lovable.app/",
    platforms: ["Web"]
  },
  {
    id: 9,
    slug: "nanobrief",
    title: "NanoBrief",
    subtitle: "AI-Powered Brief Generator",
    category: "Web App",
    tags: ["AI", "Productivity", "SaaS"],
    year: "2024",
    image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?q=80&w=2070",
    color: "from-amber-500 to-orange-500",
    featured: false,
    description: "Create professional project briefs in minutes with AI. Stop wasting hours on documentation—let AI capture every detail for you.",
    longDescription: "NanoBrief transforms how professionals create project briefs. Powered by Claude AI, it asks smart industry-specific questions and generates comprehensive, ready-to-use briefs in under 2 minutes. Supporting 9 specialized industries including Marketing, Design, Video Production, and more.",
    challenge: "Professionals spend hours writing project briefs from scratch. The process is tedious, inconsistent, and takes time away from actual creative work. Teams struggle with standardization and clients often provide vague requirements.",
    solution: "Built an AI-powered brief generator with industry-specific questionnaires designed by experts. The platform asks 5-10 smart questions and generates comprehensive, professionally formatted briefs that are ready to share instantly.",
    features: [
      "AI-powered generation with Claude AI",
      "9 specialized industry templates (Marketing, Design, Video, Legal, etc.)",
      "Smart questionnaires that capture essential details",
      "One-click shareable links (no account needed to view)",
      "PDF & Word export for professional delivery",
      "Section regeneration for perfect results",
      "Version history to track changes",
      "Custom brief builder for any industry"
    ],
    results: [
      "Briefs created in under 2 minutes vs 3+ hours",
      "60% reduction in revision cycles",
      "Consistent, professional output across teams",
      "Used by freelancers, agencies, and in-house teams"
    ],
    technologies: ["Next.js", "Claude AI", "Supabase", "Tailwind CSS", "Vercel"],
    liveUrl: "https://nanobrief.io/",
    platforms: ["Web"]
  },
  {
    id: 10,
    slug: "jeniferai",
    title: "JeniferAI",
    subtitle: "AI-Powered Executive Assistant Platform",
    category: "Web App",
    tags: ["AI", "Enterprise", "SaaS"],
    year: "2024",
    image: "https://images.unsplash.com/photo-1551434678-e076c223a692?q=80&w=2070",
    color: "from-indigo-500 to-blue-500",
    featured: false,
    description: "Transform Executive Assistants into strategic powerhouses with AI-powered automation, intelligent insights, and seamless coordination.",
    longDescription: "JeniferAI is a comprehensive command center that brings together scheduling, communication, tasks, travel, and institutional knowledge into one intuitive platform. Trusted by Fortune 500 companies and 10,000+ executive assistants worldwide.",
    challenge: "Executive teams struggle with fragmented data, manual repetitive work, inefficient task management, and costly knowledge handoffs when assistants leave. High-performing teams need better tools to operate proactively.",
    solution: "Built a unified platform that centralizes everything executive teams need—from intelligent scheduling and AI-generated meeting briefs to complete travel coordination and institutional knowledge preservation.",
    features: [
      "Smart Executive Profiles with preferences and relationship mapping",
      "AI-powered calendar optimization and conflict detection",
      "Streamlined approval workflows with deadline tracking",
      "Complete travel coordination with loyalty program integration",
      "AI-generated meeting briefs with attendee research",
      "Executive analytics for productivity optimization",
      "Smart automation with intelligent rules and triggers",
      "Mobile-first executive experience"
    ],
    results: [
      "Trusted by Fortune 500 companies",
      "10,000+ executive assistants worldwide",
      "SOC 2 Type II & ISO 27001 certified",
      "GDPR compliant enterprise security"
    ],
    technologies: ["Next.js", "React", "Node.js", "PostgreSQL", "OpenAI", "AWS"],
    liveUrl: "https://jeniferai.netlify.app/",
    platforms: ["Web", "iOS", "Android"]
  },
  {
    id: 11,
    slug: "nexurn",
    title: "Nexurn",
    subtitle: "All-in-One Business Growth Platform",
    category: "Web App",
    tags: ["SaaS", "AI", "CRM"],
    year: "2024",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2015",
    color: "from-emerald-500 to-teal-500",
    featured: false,
    description: "Run your business efficiently with unified AI tools. Empowering small businesses with all-in-one tools to drive growth, cut costs, and enhance customer engagement.",
    longDescription: "Nexurn is a comprehensive business platform designed for small businesses to get clients effortlessly. It combines CRM, booking, marketing automation, reputation management, and analytics into one unified solution powered by AI.",
    challenge: "Small businesses juggle multiple disconnected tools for CRM, scheduling, email marketing, and reputation management. This fragmentation leads to inefficiency, higher costs, and missed opportunities.",
    solution: "Created an all-in-one platform that unifies booking, CRM, email/SMS marketing, reputation management, live chat, and business automation—all powered by AI to help small businesses grow efficiently.",
    features: [
      "Booking and appointment scheduling",
      "Powerful CRM for contact and pipeline management",
      "Full business metrics dashboard and reporting",
      "Reputation management and reviews control",
      "2-way SMS marketing",
      "Email marketing with newsletters and automation",
      "Survey and form builder",
      "Live web chat for customer support",
      "Industry-leading workflow automation"
    ],
    results: [
      "Trusted by 1000+ brands worldwide",
      "Unified platform replacing 5+ tools",
      "Improved lead response times",
      "Higher conversion rates for clients"
    ],
    technologies: ["React", "Node.js", "PostgreSQL", "AI Integration", "Twilio", "AWS"],
    liveUrl: "https://nexurn.com/",
    platforms: ["Web"]
  },
  {
    id: 12,
    slug: "scanlify",
    title: "Scanlify",
    subtitle: "Business Card Scanning & CRM",
    category: "Web App",
    tags: ["Productivity", "CRM", "Networking"],
    year: "2024",
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=2070",
    color: "from-violet-500 to-purple-500",
    featured: false,
    description: "The modern way to scan business cards, manage contacts, and run campaigns. Effortless CRM for individuals, professionals, and teams.",
    longDescription: "Scanlify streamlines networking by allowing users to scan business cards, automatically organize contacts, and run personalized email campaigns—all from one intuitive platform with a spreadsheet-like interface.",
    challenge: "Professionals collect business cards at events but struggle to digitize, organize, and follow up with contacts efficiently. Manual data entry is time-consuming and leads to missed opportunities.",
    solution: "Built a modern business card scanning platform with drag-and-drop functionality, automatic contact organization, and integrated campaign management to turn networking into actionable relationships.",
    features: [
      "Scan up to 100 business cards at once",
      "Drag-and-drop functionality",
      "Automatic contact organization",
      "Create personalized email campaigns",
      "Track campaign performance",
      "Export contacts to CSV",
      "Real-time contact management",
      "Advanced filtering and editing",
      "Spreadsheet-like interface",
      "Business activity visualization and insights"
    ],
    results: [
      "Streamlined networking workflow",
      "Actionable insights and reports",
      "Improved follow-up rates",
      "Time saved on manual data entry"
    ],
    technologies: ["Next.js", "React", "Supabase", "OCR Technology", "Tailwind CSS", "Vercel"],
    liveUrl: "https://scanlify.io/",
    platforms: ["Web"]
  }
]
